#!/bin/bash

### Job name
#PBS -N rnaseqc

### Specify email address to use for notification.
#PBS -M bmlau@email.arizona.edu

### Request email when job ends
#PBS -m ea

### Specify the PI group found with va command
#PBS -W group_list=mfh

### Set the queue to submit this job.
#PBS -q standard

### Set the number of nodes and cpus that will be used.
#PBS -l select=1:ncpus=28:mem=28gb:pcmem=6gb
#PBS -l place=pack:shared

### Specify up to a maximum of 1600 hours total cpu time
#PBS -l cput=050:0:0

### Specify up to a maximum of 240 hours walltime for the job
#PBS -l walltime=0:50:0

### Define path for stdout and stderr
#PBS -o .
#PBS -j oe

### Move to *current* directory - assuming this is where you want to run!
cd $PBS_O_WORKDIR

/unsupported/exome/WES_Research/develop/rnaseqc/rnaseqc.v2.3.4.linux /rsgrps/ruichang/bmlau/Gencode_v25/gencode.v25.GRCh38.genes.gtf *.bam --coverage rnaseqc_output


