#!/bin/bash

### Run FastQC on all reads in working directory.
### Intended for use on MiSeq projects, where FastQC
### does not get run during read production process.
### Will run on all reads in directory, including
### untrimmed.

### Job name
#PBS -N fastqc

### Specify email address to use for notification.
#PBS -M bmlau@email.arizona.edu

### Request email when job ends
#PBS -m ea

### Specify the PI group found with va command
#PBS -W group_list=mfh

### Set the queue to submit this job.
#PBS -q standard

### Set the number of nodes and cpus that will be used.
#PBS -l select=1:ncpus=28:mem=28gb:pcmem=6gb
#PBS -l place=pack:shared

### Specify up to a maximum of 1600 hours total cpu time
#PBS -l cput=672:0:0

### Specify up to a maximum of 240 hours walltime for the job
#PBS -l walltime=24:0:0

### Define path for stdout and stderr
#PBS -o .
#PBS -j oe

### Move to *current* directory - assuming this is where you want to run!
cd $PBS_O_WORKDIR

### Profile job
echo Running on host `hostname`
echo Time is `date`
echo Directory is `pwd`
echo


### Set log file name
LOGFILE=$PBS_JOBID.fastqc.OU

### Profile job
echo Running on host `hostname` > $LOGFILE
echo Time is `date` >> $LOGFILE
echo Directory is `pwd` >> $LOGFILE
echo >> $LOGFILE

### Make output directory
date=`date +%F`
mkdir fastqc_out_$date

### Run jobs (one for R1, one for R2)

/unsupported/exome/WES_Research/develop/FastQC_v0.11.8/fastqc \
--casava --nogroup --outdir fastqc_out_$date \
--dir /rsgrps/ruichang/bmlau/tmp \
-t 4 \
*R1*.fastq.gz >> $LOGFILE 2>&1

/unsupported/exome/WES_Research/develop/FastQC_v0.11.8/fastqc \
--casava --nogroup --outdir fastqc_out_$date \
--dir /rsgrps/ruichang/bmlau/tmp \
-t 4 \
*R2*.fastq.gz >> $LOGFILE 2>&1

### Get time stamp again
date >> $LOGFILE

